### ISSUE TITLE
Getting "Super expression must either be null or a function, not undefined" when extending a Phaser class

### ISSUE THREAD

**Issue by pparke** [rblopes/slush-phaser-plus#8]
First, just want to say I love the work you've done here and I've been using your generator exclusively for my Phaser projects.

I've just begun setting up a new project and encountered this error while extending a Phaser class in the same way that I have previously using this generator.  Thinking it may have been something that I did, I set up a fresh project and created a new file extending the Phaser.Tilemap class and sure enough I immediately encountered the same error.  Extending something like Phaser.Group works fine.  Difference seems to be that I'm using the latest version of your generator for this project.  Any help you could provide would be greatly appreciated.

**Comment by rblopes** [comment]
Hi, @pparke. Sorry for the late reply and thanks for choosing `slush-phaser-plus`.

Just to be sure if the issue is with the generator or the template project, I have a few questions.

* What updated? The generator or the created project dependencies?

* When running the generator, which option did you chose? I'm sure that at least the “no physics” option lacks Tilemap support, besides it having nothing to do with physics engines but Tilemaps were coupled to Arcade Physics in the past.

**Comment by pparke** [comment]
Sorry for the lack of details, I had thought it was resolved after updating the generator but it turns out that the issue is still occurring. I think that you're right about the "no physics" option being the cause since I am able to get it working when starting a new project and selecting arcade physics.  Thanks for getting back to me :)
